# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15jBGFethT9wTjBeGYBp47ITIum7qf7UM
"""

# ---------------------------
# 1. Install packages
# ---------------------------
!pip install streamlit pyngrok pandas scikit-learn requests

# ---------------------------
# 2. Imports
# ---------------------------
import pandas as pd
import numpy as np
import ast
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import requests
import streamlit as st
from pyngrok import ngrok

# ---------------------------
# 3. Load CSV files safely (Arabic & messy CSVs)
# ---------------------------
movies_file = "/content/movies_metadata.csv"  # main movie CSV
links_file  = "/content/links.csv"   # links CSV

movies = pd.read_csv(movies_file, encoding='utf-8', engine='python', quotechar='"', on_bad_lines='skip')
links  = pd.read_csv(links_file, encoding='utf-8')

# ---------------------------
# 4. Clean IDs and merge
# ---------------------------
movies['id'] = pd.to_numeric(movies['id'], errors='coerce')
links['movieId'] = pd.to_numeric(links['movieId'], errors='coerce')

movies = movies.dropna(subset=['id'])
links = links.dropna(subset=['movieId'])

movies['id'] = movies['id'].astype(int)
links['movieId'] = links['movieId'].astype(int)

movies = movies.merge(links, left_on='id', right_on='movieId', how='left')

# ---------------------------
# 5. Poster URL
# ---------------------------
TMDB_API_KEY = "YOUR_TMDB_API_KEY"  # Replace with your TMDb API key

def get_poster_from_tmdb(tmdb_id):
    if pd.isna(tmdb_id):
        return ""
    try:
        url = f"https://api.themoviedb.org/3/movie/{int(tmdb_id)}?api_key={TMDB_API_KEY}&language=en-US"
        data = requests.get(url).json()
        if 'poster_path' in data and data['poster_path']:
            return f"https://image.tmdb.org/t/p/w500{data['poster_path']}"
    except:
        return ""
    return ""

movies['poster_full'] = movies['poster_path'].apply(
    lambda x: f"https://image.tmdb.org/t/p/w500{x}" if pd.notnull(x) else ""
)
movies['poster_full'] = movies.apply(
    lambda row: get_poster_from_tmdb(row['tmdbId']) if row['poster_full'] == "" else row['poster_full'], axis=1
)

# ---------------------------
# 6. Preprocess text (overview + genres)
# ---------------------------
def extract_genres(genres):
    try:
        genre_list = ast.literal_eval(str(genres))
        return " ".join([g['name'] for g in genre_list])
    except:
        return ""

movies['genres_str'] = movies['genres'].apply(extract_genres)
movies['combined'] = movies['overview'].fillna('') + " " + movies['genres_str']

# ---------------------------
# 7. TF-IDF and cosine similarity
# ---------------------------
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(movies['combined'])
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

title_to_index = pd.Series(movies.index, index=movies['title']).to_dict()

# ---------------------------
# 8. Recommendation function
# ---------------------------
def recommend_movies(movie1, movie2, top_n=3):
    idx1 = title_to_index.get(movie1)
    idx2 = title_to_index.get(movie2)
    if idx1 is None or idx2 is None:
        return []

    sim_scores = (cosine_sim[idx1] + cosine_sim[idx2]) / 2
    sim_scores[idx1] = 0
    sim_scores[idx2] = 0

    top_indices = sim_scores.argsort()[-top_n:][::-1]
    results = []
    for i in top_indices:
        movie = movies.iloc[i]
        results.append({
            "title": movie['title'],
            "overview": movie['overview'],
            "rating": movie['vote_average'],
            "poster": movie['poster_full']
        })
    return results

# ---------------------------
# Streamlit UI
# ---------------------------
st.title("🎬 Movie Recommender for Two Users")
st.write("Select two movies and get top 3 movies similar to both.")

movie_list = movies['title'].tolist()
movie1 = st.selectbox("Movie 1", movie_list)
movie2 = st.selectbox("Movie 2", movie_list)

# Display input movie posters
col1, col2 = st.columns(2)
with col1:
    poster1 = movies.loc[movies['title']==movie1, 'poster_full'].values[0]
    if poster1:
        st.image(poster1, width=200)
    st.write(movie1)
with col2:
    poster2 = movies.loc[movies['title']==movie2, 'poster_full'].values[0]
    if poster2:
        st.image(poster2, width=200)
    st.write(movie2)

# Show recommendations
if st.button("Recommend"):
    recommendations = recommend_movies(movie1, movie2)
    for rec in recommendations:
        st.markdown("---")
        st.subheader(f"{rec['title']} ⭐ {rec['rating']}")
        st.image(rec['poster'], width=200)
        st.write(rec['overview'])